services:
  wake-on-http:
    build:
      context: .
      dockerfile: Dockerfile
    image: wake-on-http:latest
    container_name: wake-on-http
    network_mode: host
    volumes:
      - /path/to/services:/wake-on-http/services:ro     # replace
      - /path/to/notifiers:/wake-on-http/notifiers:ro   # replace
      - /path/to/templates:/wake-on-http/templates:ro   # replace
    environment:
      - DIRECT="wake.example.com"   # replace
      - SERVER_PORT=5555
      - LOG_LEVEL=INFO
      - TZ=GMT
    restart: unless-stopped
